<a href="https://colab.research.google.com/github/git933/Machine-Learning/blob/main/01_Dimension_and_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 1D 배열

In [17]:
import numpy as np

# 하나의 행으로 벡터 생성
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [18]:
# 하나의 열로 벡터 생성
vector_column = np.array([[1], 
                         [2], 
                         [3]])
vector_column

array([[1],
       [2],
       [3]])

In [19]:
print(type(vector_row))
print(type(vector_column))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>




---



# 2D 배열

In [20]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [21]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])



---



# 0으로만 구성된 matrix 생성

In [22]:
zero_matrix = np.zeros((3, 2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])



---



# 1로만 구성된 matrix 생성

In [23]:
one_matrix = np.ones((3, 2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



---



# 배열 정보 확인

In [24]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
matrix.shape  # 행렬의 크기

(3, 4)

In [25]:
matrix.size # 원소 개수

12

In [26]:
matrix.ndim # 차원 수

2

In [27]:
matrix.dtype  # 데이터 타입

dtype('int64')

In [28]:
matrix + 100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])



---



# 배열 크기 변경

In [29]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

matrix.reshape(2, 6)  # 크기 변경

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
matrix.size

12

In [31]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
matrix.ravel()  # return a flattened matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])



---



# 배열 전치

In [35]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
np.array([1, 2, 3, 4, 5, 6]).T  # 벡터 전치

array([1, 2, 3, 4, 5, 6])

In [37]:
np.array([[1, 2, 3, 4, 5, 6]]).T  # 행벡터 전치

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])



---



# 행렬 펼치기

In [38]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])



---



In [40]:
from IPython.display import Image



---



# 1D 배열

In [41]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [42]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [43]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [44]:
a.shape

(3,)

In [45]:
b.shape

(3, 1)

In [46]:
a1 = np.arange(1, 13) # 1 ~ 12
a1.shape

(12,)

numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

Return evenly spaced values within a given interval.



---



# 2D 배열

In [47]:
a = np.array([[1, 2],
              [1, 2],
              [1, 2]])
a

array([[1, 2],
       [1, 2],
       [1, 2]])

In [48]:
a_0 = np.zeros((3, 2))
a_0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
a_1 = np.ones((3, 2))
a_1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
a.shape

(3, 2)

In [51]:
a_0.shape

(3, 2)

In [52]:
a_1.shape

(3, 2)

In [53]:
a.ndim

2

In [54]:
a_0.ndim

2

In [55]:
a.dtype

dtype('int64')

In [56]:
a_1.dtype

dtype('float64')

In [57]:
a_0.dtype

dtype('float64')



---



# reshape() : 배열 바꾸기

In [58]:
a1_2d = a1.reshape(3, 4)
a1_2d.shape

(3, 4)

In [59]:
a1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a1.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

열은 4개로 고정, 행은 적당히 만들어짐

In [61]:
a1.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

행은 3개로 고정, 열은 적당히 만들어짐

In [62]:
a1.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [63]:
a1.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

행은 2개로 고정, 열은 적당히 만들어짐

**reshape에서 -1 : 적당히 지정된다는 뜻**



---



# reshape() 다른 방향으로

In [64]:
a1.reshape(3, 4)  # reshapes or 'fills in' row by row

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
a1.reshape(3, 4, order = 'C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a1.reshape(3, 4, order = 'F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [67]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
a1.shape

(12,)

In [69]:
a1_1_by_12 = a1.reshape(1, -1)
a1_1_by_12

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [70]:
a1_1_by_12.shape

(1, 12)



---



# flatten(), ravel()로 1D array 사용

In [71]:
a1_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

ravel() : 다차원을 1차원으로 변경

In [72]:
a1_2d.ravel()  # default order = 'C'

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
a1_2d.ravel(order = 'F')  # ravel by column

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])



---



# concatenate / stack을 위한 np.stack() & np.hstack

In [76]:
a1 = np.arange(1, 13)
a2 = np.arange(13, 25)

In [77]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
a2

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
stack0 = np.stack((a1, a1, a2, a2))
stack0.shape

(4, 12)

In [80]:
stack_long = np.hstack((a1, a2))
stack_long.shape

(24,)



---



# 3차원 배열 생성

In [82]:
a1 = np.arange(1, 13).reshape(3, -1)
a2 = np.arange(13, 25).reshape(3, -1)

In [83]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [85]:
a3_0 = np.stack((a1, a2)) # dimension = 0
a3_1 = np.stack((a1, a2), axis = 1) # dimension 1
a3_2 = np.stack((a1, a2), axis = 2) # dimension 2

In [86]:
a3_0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [87]:
a3_1

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [88]:
a3_2

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])



---



# 배열의 차원 인덱싱

In [89]:
a3_0[0, :, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
a3_0[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a3_0[:, 0, :]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [92]:
a3_0[:, :, 0]

array([[ 1,  5,  9],
       [13, 17, 21]])



---



# flatten(), ravel() 배열 펼치기

In [93]:
a3_0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [94]:
a3_0.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [96]:
a3_0.ravel(order = 'F')

array([ 1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10, 22,  3, 15,  7, 19, 11,
       23,  4, 16,  8, 20, 12, 24])

In [97]:
a3_0.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [98]:
a3_0.flatten(order = 'F')

array([ 1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10, 22,  3, 15,  7, 19, 11,
       23,  4, 16,  8, 20, 12, 24])



---



# reshape()로 3차원 바꾸기

In [99]:
a3_0.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [100]:
a3_0.reshape(4, -1, order = 'F')

array([[ 1,  9,  6,  3, 11,  8],
       [13, 21, 18, 15, 23, 20],
       [ 5,  2, 10,  7,  4, 12],
       [17, 14, 22, 19, 16, 24]])

In [101]:
a3_0.reshape(4, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])



---



# 배열의 전치 (transpose)

In [102]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])