<a href="https://colab.research.google.com/github/git933/Machine-Learning/blob/main/06_feature_engineering_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# 데이터 전처리

In [8]:
import numpy as np
import pandas as pd



---



**결측치(null값) 처리**

In [9]:
titanic = pd.read_csv('/content/drive/MyDrive/MachineLearning_class/고우주-1일차_실습코드/01_Data Structures/data/titanic.csv')
titanic.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [10]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

isnull = isna



---



**결측치 제외**

In [12]:
titanic.dropna(axis = 0)  # nan값 삭제

PassengerId  Survived  Pclass  ...     Fare        Cabin  Embarked
1              2         1       1  ...  71.2833          C85         C
3              4         1       1  ...  53.1000         C123         S
6              7         0       1  ...  51.8625          E46         S
10            11         1       3  ...  16.7000           G6         S
11            12         1       1  ...  26.5500         C103         S
..           ...       ...     ...  ...      ...          ...       ...
871          872         1       1  ...  52.5542          D35         S
872          873         0       1  ...   5.0000  B51 B53 B55         S
879          880         1       1  ...  83.1583          C50         C
887          888         1       1  ...  30.0000          B42         S
889          890         1       1  ...  30.0000         C148         C

[183 rows x 12 columns]

In [14]:
titanic.dropna(axis = 1)  # 누락된 값이 있는 열을 삭제

PassengerId  Survived  Pclass  ... Parch            Ticket     Fare
0              1         0       3  ...     0         A/5 21171   7.2500
1              2         1       1  ...     0          PC 17599  71.2833
2              3         1       3  ...     0  STON/O2. 3101282   7.9250
3              4         1       1  ...     0            113803  53.1000
4              5         0       3  ...     0            373450   8.0500
..           ...       ...     ...  ...   ...               ...      ...
886          887         0       2  ...     0            211536  13.0000
887          888         1       1  ...     0            112053  30.0000
888          889         0       3  ...     2        W./C. 6607  23.4500
889          890         1       1  ...     0            111369  30.0000
890          891         0       3  ...     0            370376   7.7500

[891 rows x 9 columns]

In [15]:
titanic.dropna(how = 'all') # 모든 열이 nan인 행 삭제

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [16]:
titanic.dropna(thresh = 4)  # nan 아닌 값이 네 개보다 작은 행을 삭제

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [17]:
titanic.dropna(subset = ['Age'])  # 특정 열에 nan이 있는 행만 삭제 (age)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
885          886         0       3  ...  29.1250   NaN         Q
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[714 rows x 12 columns]



---



**대체값 삽입 (imputation)**

In [18]:
# 행의 평균으로 누락된 값 대체
from sklearn.impute import SimpleImputer

imr = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imr = imr.fit(titanic[['Age']])
titanic['Age_imp'] = imr.transform(titanic[['Age']])
titanic.head()

PassengerId  Survived  Pclass  ... Cabin Embarked  Age_imp
0            1         0       3  ...   NaN        S     22.0
1            2         1       1  ...   C85        C     38.0
2            3         1       3  ...   NaN        S     26.0
3            4         1       1  ...  C123        S     35.0
4            5         0       3  ...   NaN        S     35.0

[5 rows x 13 columns]

In [19]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Age_imp          0
dtype: int64

In [20]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

iimr = IterativeImputer()
titanic['Age_Iter'] = iimr.fit_transform(titanic[['Age']])
titanic.head()

PassengerId  Survived  Pclass  ... Embarked Age_imp  Age_Iter
0            1         0       3  ...        S    22.0      22.0
1            2         1       1  ...        C    38.0      38.0
2            3         1       3  ...        S    26.0      26.0
3            4         1       1  ...        S    35.0      35.0
4            5         0       3  ...        S    35.0      35.0

[5 rows x 14 columns]

In [21]:
from sklearn.impute import KNNImputer # KNN으로 누락 값 채움

kimr = KNNImputer()
titanic['Age_kimr'] = kimr.fit_transform(titanic[['Age']])
titanic.head()

PassengerId  Survived  Pclass  ... Age_imp Age_Iter  Age_kimr
0            1         0       3  ...    22.0     22.0      22.0
1            2         1       1  ...    38.0     38.0      38.0
2            3         1       3  ...    26.0     26.0      26.0
3            4         1       1  ...    35.0     35.0      35.0
4            5         0       3  ...    35.0     35.0      35.0

[5 rows x 15 columns]

In [22]:
titanic['Age'].fillna(titanic['Age'].mean())  # fillna로 누락된 값 채우기 가능

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [23]:
titanic['Age'].fillna(method = 'bfill') # = (method = 'backfill)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    26.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [24]:
titanic['Age'].fillna(method = 'ffill') # = (method = 'pad')

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    19.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64



---



# 범주형 (categorical) 데이터 다루기

**pandas map() 매핑**

In [25]:
titanic['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [26]:
titanic['Embarked'].isnull().sum()

2

In [27]:
titanic.dropna(inplace = True)
titanic['Embarked'].isnull().sum()

0

In [28]:
mapping = {'C' : 0,
           'Q' : 1,
           'S' : 2}
titanic['Embarked_map'] = titanic['Embarked'].map(mapping)
titanic.head()

PassengerId  Survived  Pclass  ... Age_Iter Age_kimr  Embarked_map
1             2         1       1  ...     38.0     38.0             0
3             4         1       1  ...     35.0     35.0             2
6             7         0       1  ...     54.0     54.0             2
10           11         1       3  ...      4.0      4.0             2
11           12         1       1  ...     58.0     58.0             2

[5 rows x 16 columns]

**class 레이블 인코딩**

In [29]:
from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()
y = class_le.fit_transform(titanic['Embarked'].values)
y

array([0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 0, 2, 0])

In [30]:
# 거꾸로 매핑
class_le.inverse_transform(y)

array(['C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S',
       'S', 'S', 'C', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S',
       'S', 'S', 'C', 'C', 'S', 'S', 'C', 'C', 'S', 'C', 'C', 'C', 'S',
       'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'C',
       'C', 'S', 'C', 'S', 'C', 'C', 'C', 'C', 'S', 'C', 'C', 'S', 'C',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'C', 'C',
       'S', 'C', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C',
       'S', 'S', 'S', 'C', 'C', 'S', 'C', 'S', 'C', 'S', 'S', 'C', 'S',
       'S', 'S', 'S', 'C', 'S', 'C', 'S', 'C', 'C', 'C', 'S', 'S', 'S',
       'S', 'C', 'C', 'S', 'C', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'S',
       'C', 'C', 'C', 'C', 'C', 'S', 'S', 'C', 'C', 'S', 'S', 'C', 'S',
       'C', 'S', 'S', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S',
       'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'C

In [31]:
class_le.classes_

array(['C', 'Q', 'S'], dtype=object)

**one-hot-encoding**

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
titanic['Pclass'].value_counts()

1    158
2     15
3     10
Name: Pclass, dtype: int64

In [34]:
le = LabelEncoder()
le.fit_transform(titanic['Pclass'])

array([0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [35]:
pd.get_dummies(titanic[['Sex', 'Embarked']])  # 가변수 생성 : 결측값을 제외하고 0과 1로 구성된 더미 생성

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
1             1         0           1           0           0
3             1         0           0           0           1
6             0         1           0           0           1
10            1         0           0           0           1
11            1         0           0           0           1
..          ...       ...         ...         ...         ...
871           1         0           0           0           1
872           0         1           0           0           1
879           1         0           1           0           0
887           1         0           0           0           1
889           0         1           1           0           0

[183 rows x 5 columns]

In [36]:
# 다중 공선성 문제(독립변수들 간 지나친 연관성 가지는 문제) 처리
pd.get_dummies(titanic[['Sex', 'Embarked']], drop_first = True)

Sex_male  Embarked_Q  Embarked_S
1           0           0           0
3           0           0           1
6           1           0           1
10          0           0           1
11          0           0           1
..        ...         ...         ...
871         0           0           1
872         1           0           1
879         0           0           0
887         0           0           1
889         1           0           0

[183 rows x 3 columns]

In [37]:
ohe = OneHotEncoder(categories = 'auto', drop = 'first')
titanic['Sex_ohe'] = ohe.fit_transform(titanic[['Sex']]).toarray()
titanic.head()

PassengerId  Survived  Pclass  ... Age_kimr Embarked_map  Sex_ohe
1             2         1       1  ...     38.0            0      0.0
3             4         1       1  ...     35.0            2      0.0
6             7         0       1  ...     54.0            2      1.0
10           11         1       3  ...      4.0            2      0.0
11           12         1       1  ...     58.0            2      0.0

[5 rows x 17 columns]



---



# 데이터셋을 훈련과 테스트로 나누기

In [38]:
titanic.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], axis = 1, inplace = True)

In [39]:
from sklearn.model_selection import train_test_split

X = titanic.drop(['Survived'], axis = 1)
y = titanic['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(128, 11)
(55, 11)
(128,)
(55,)




---



# 특성 스케일 (feature scaling)

**최소-최대 스케일링 (min-max scaling)**

$x^{(i)}_{norm} = \dfrac{x^{(i)}-x_{min}}{x_{max}-x_{min}}$

In [40]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

X_train_norm

array([[0.69481982, 0.5       , 0.02898551, ..., 0.02898551, 1.        ,
        0.        ],
       [0.27477477, 0.        , 0.60869565, ..., 0.60869565, 0.5       ,
        1.        ],
       [0.60247748, 0.        , 0.62318841, ..., 0.62318841, 1.        ,
        1.        ],
       ...,
       [0.64864865, 0.        , 0.53623188, ..., 0.53623188, 1.        ,
        0.        ],
       [0.30067568, 0.        , 0.8115942 , ..., 0.8115942 , 1.        ,
        0.        ],
       [0.92567568, 1.        , 0.36231884, ..., 0.36231884, 1.        ,
        0.        ]])

**표준화 (standardization)**

$x^{(i)}_{std} = \dfrac{x^{(i)}-\mu_x}{\sigma_x}$

In [41]:
from sklearn.preprocessing import  StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

X_train_std

array([[ 0.66008084,  1.42394828, -2.01994572, ..., -2.01994572,
         0.70511099, -1.1160708 ],
       [-0.8588559 , -0.38065944,  0.54157059, ...,  0.54157059,
        -0.36934385,  0.8960005 ],
       [ 0.32615909, -0.38065944,  0.60560849, ...,  0.60560849,
         0.70511099,  0.8960005 ],
       ...,
       [ 0.49311996, -0.38065944,  0.22138105, ...,  0.22138105,
         0.70511099, -1.1160708 ],
       [-0.76519492, -0.38065944,  1.43810129, ...,  1.43810129,
         0.70511099, -1.1160708 ],
       [ 1.49488521,  3.228556  , -0.54707384, ..., -0.54707384,
         0.70511099, -1.1160708 ]])

**표준화와 정규화의 차이**

In [42]:
ex = np.array([0, 1, 2, 3, 4, 5])

# 표준화
print('표준화 : ', (ex - ex.mean()) / ex.std())

# 정규화
print('정규화 : ', (ex - ex.min()) / (ex.max() - ex.min()))

표준화 :  [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
정규화 :  [0.  0.2 0.4 0.6 0.8 1. ]


**Robust scaler**

$ x_{robust}^{(i)} = \dfrac{x^{(i)} - q_2}{q_3 - q_1}$

In [43]:
from sklearn.preprocessing import RobustScaler

rbs = RobustScaler()
X_train_robust = rbs.fit_transform(X_train)
X_test_robust = rbs.transform(X_test)

In [44]:
(ex - np.percentile(ex, 50)) / (np.percentile(ex, 75) - np.percentile(ex, 25))

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

**MaxAbs Scaler**

각 데이터를 최대 절댓값으로 나눔

최댓값 = 1

범위 : [-1, 1]

In [45]:
from sklearn.preprocessing import MaxAbsScaler

mas = MaxAbsScaler()
X_train_maxabs = mas.fit_transform(X_train)
X_test_maxabs = mas.transform(X_test)

In [46]:
ex / np.max(np.abs(ex))

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

**다양한 scaler 함수 사용**

In [47]:
from sklearn.preprocessing import scale, minmax_scale, robust_scale, maxabs_scale

print('StandardScaler : ', scale(ex)) # StandardScaler : scale()
print('MinMaxScaler : ', minmax_scale(ex))  # MinMaxScaler : minmax_scale()
print('RobustScaler : ', robust_scale(ex))  # RobustScaler : robust_scale()
print('MaxAbsScaler : ', maxabs_scale(ex))  # MaxAbsScaler : maxabs_scale()

StandardScaler :  [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
MinMaxScaler :  [0.  0.2 0.4 0.6 0.8 1. ]
RobustScaler :  [-1.  -0.6 -0.2  0.2  0.6  1. ]
MaxAbsScaler :  [0.  0.2 0.4 0.6 0.8 1. ]


**Normalizer**

- 샘플별로 정규화 시행

- 희소 행렬도 처리 가능

In [48]:
from sklearn.preprocessing import Normalizer

nrm = Normalizer()
X_train_l2 = nrm.fit_transform(X_train)

In [49]:
ex_2f = np.vstack((ex[1:], ex[1:]**2))
ex_2f

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

**L2 Norm 공식**

$ \lVert \boldsymbol{x} \rVert_2 = \sqrt{x_1^2 + x_2^2 + \cdots + x_n^2} $

In [51]:
l2_norm = np.sqrt(np.sum(ex_2f ** 2, axis = 1))
print(l2_norm)
ex_2f / l2_norm.reshape(-1, 1)

[ 7.41619849 31.28897569]


array([[0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986],
       [0.03196014, 0.12784055, 0.28764125, 0.51136222, 0.79900347]])

**L1 Norm 공식**

$ \lVert \boldsymbol{x} \rVert_1 = \lvert x_1 \rvert + \lvert x_2 \rvert + \cdots + \lvert x_n \rvert $

In [52]:
l1_norm = np.sum(np.abs(ex_2f), axis = 1)
print(l1_norm)
ex_2f / l1_norm.reshape(-1, 1)

[15 55]


array([[0.06666667, 0.13333333, 0.2       , 0.26666667, 0.33333333],
       [0.01818182, 0.07272727, 0.16363636, 0.29090909, 0.45454545]])

In [53]:
max_norm = np.max(np.abs(ex_2f), axis = 1)
print(max_norm)
ex_2f / max_norm.reshape(-1, 1)

[ 5 25]


array([[0.2 , 0.4 , 0.6 , 0.8 , 1.  ],
       [0.04, 0.16, 0.36, 0.64, 1.  ]])